### ISSUE TITLE
Failed to flush the buffer GRPC::Unavailable 14:Deadline exceeded

### ISSUE THREAD

**Issue by btj** [GoogleCloudPlatform/google-fluentd#258] opened 2020-04-09 09:34 UTC
Since yesterday around 2pm GMT, I'm getting `failed to flush the buffer. [...] error_class=GRPC::Unavailable error="14:Deadline Exceeded"`.

Manually creating a log entry using `gcloud logging write my-test-log "A simple entry."` does work.

**Comment by btj** [comment] 2020-04-09 09:58
Update: I reset the VM and now it works fine again...

**Comment by bplotnick** [comment] 2020-04-10 23:31
We also saw this: https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/393

**Comment by igorpeshansky** [comment] 2020-04-11 01:53
Duplicate of GoogleCloudPlatform/google-fluentd#258.

**Closed by igorpeshansky** 2020-04-11 01:53 UTC
