### ISSUE TITLE
unexpected error error_class=ArgumentError error="wrong number of arguments ( given 2, expected 1; required keyword: docstring)"

### ISSUE THREAD

**Issue by niciliketo** [GoogleCloudPlatform/google-fluentd#211] opened 2019-10-13 11:03 UTC
Since upgrading to the latest version google-fluentd we see the service starting/crashing continuously stack trace:
`````
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/root_agent.rb:191:in `each'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/root_agent.rb:191:in `block in lifecycle'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/root_agent.rb:178:in `each'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/root_agent.rb:178:in `lifecycle'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/root_agent.rb:202:in `start'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/engine.rb:274:in `start'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/engine.rb:219:in `run'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/supervisor.rb:808:in `run_engine'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/supervisor.rb:551:in `block in run_worker'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/supervisor.rb:733:in `main_process'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/supervisor.rb:546:in `run_worker'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/lib/flu
ent/command/fluentd.rb:320:in `<top (required)>'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/ker
nel_require.rb:54:in `require'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/ker
nel_require.rb:54:in `require'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.5.0/gems/fluentd-1.6.3/bin/flu
entd:8:in `<top (required)>'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/bin/fluentd:23:in `load'
  2019-10-13 10:48:53 +0000 [error]: #0 /opt/google-fluentd/embedded/bin/fluentd:23:in `<top (required)>'
  2019-10-13 10:48:53 +0000 [error]: #0 /usr/sbin/google-fluentd:7:in `load'
  2019-10-13 10:48:53 +0000 [error]: #0 /usr/sbin/google-fluentd:7:in `<main>'
2019-10-13 10:48:53 +0000 [error]: #0 unexpected error error_class=ArgumentError error="wrong number of arguments (
given 2, expected 1; required keyword: docstring)"
  2019-10-13 10:48:53 +0000 [error]: #0 suppressed same stacktrace

**Comment by jkschulz** [comment] 2019-10-15 04:13
Hi, thanks for the report. I'll need some additional info to look into this. Can you please share any steps you have to help me reproduce, relevant details about your environment (google-fluentd version before and after upgrade, config, OS), and the full google-fluentd logs?

**Comment by jkschulz** [comment] 2020-10-02 20:30
I'm going to close this since it's been ~a year with no update. Please re-open if you're still experiencing the issue.

**Closed by jkschulz** 2020-10-02 20:30 UTC
